global using QRCode.Application;
global using QRCode.Infrastructure;
global using Microsoft.AspNetCore.Mvc;
global using MediatR;
global using QRCode.Application.UseCases.Users.Queries;
global using QRCode.API.DTOs;
global using QRCode.Application.UseCases.Users.Commands;
global using QRCoder;
global using System.Drawing;